apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://raw.githubusercontent.com/istio/istio/release-1.24/samples/addons
    targetRevision: HEAD
    path: .
    directory:
      include: "prometheus.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true